version: '3.6'
services:
  traffic_generator:
    image: traffic_generator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TARGET_URL: "https://www.gov.uk.glasswall-icap.com/"
      HEADLESS: "1"
