version: '3.6'
services:
  traffic-generator:
    image: traffic-generator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOV_UK_URL: "https://www.gov.uk.glasswall-icap.com/"
      FILE_DROP_URL: "https://glasswall-file-drop.azurewebsites.net"
      HEADLESS: "1"
      NUM_FILES: "10"
      LOOP: "1"
      RUN_FOR_MINS: "4"
      SHIP_TO_ELASTIC: "1"
      ELASTIC_HOST: "localhost"
      ELASTIC_PORT: "9200"
      ELASTIC_USER: "elastic"
      ELASTIC_PASSWORD: "update_with_elastic_pwd"
      INDEX_NAME: "tg_test_results"
