apiVersion: batch/v1
kind: Job
metadata:
  name: traffic-generator
  labels:
    env: test
    jobgroup: traffic-generator
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: traffic-generator
      labels:
        jobgroup: traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: pranaysahith/traffic-generator-gov-uk:0.0.4
        imagePullPolicy: IfNotPresent
        env:
          - name: GOV_UK_URL
            value: "https://www.gov.uk.glasswall-icap.com/"
          - name: FILE_DROP_URL
            value: "https://glasswall-file-drop.azurewebsites.net"
          - name: HEADLESS
            value: "1"
          - name: NUM_FILES
            value: "10"
          - name: LOOP
            value: "1"
          - name: RUN_FOR_MINS
            value: "10"
          - name: SHIP_TO_ELASTIC
            value: "1"
          - name: ELASTIC_HOST
            value: "quickstart-es-http.elastic-system.svc.cluster.local"
          - name: ELASTIC_PORT
            value: "9200"
          - name: ELASTIC_USER
            value: "elastic"
          - name: ELASTIC_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: "elastic-password" 
                  name: "elastic-secret"
        workingDir: /app
      restartPolicy: Never  
---