name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Installing the pre-requiste
        run: sudo apt-get install python3-setuptools && pip3 install wheel
      - name: Iniatilize the tool
        run: pip3 install gittyleaks
      - name: Perform Scan
        run: python3 -m gittyleaks -repo .
